---
- hosts: dev
  ignore_errors: yes
  become: True
  tasks:
  - name: 'Deploying image'
    command: kubectl apply -f myapp.yml
  - name: Create a Service object from an inline definition
    command: kubectl expose pod myapp --type=NodePort --target-port=8080 --port=8080
