---
- hosts: dev
  become: True
  tasks:
  - name: 'Installing Python3'
    yum:
      name: python3
      state: present
  - name: 'Installing openshift module'
    command: pip3 install openshift
  - name: 'Installing PyYAML'
    command: pip3 install PyYAML
  - name: 'Creating deployment '
    command: kubectl create deployment server --image=dhanrajranvirkar/myapp:${image_version}
  - name: 'Expose Deployment'
    command: kubectl expose deployment server --type=loadBalancer --target-port=8080 --port=8888
