---
- hosts: dev
  become: True
  tasks:
  - name: 'Creating deployment '
    community.kubernetes.k8s:
      state: present
      src: myapp.yml
  - name: 'exporting deployment'
    community.kubernetes.k8s:
      state: present
      src: myappserver.yml
