---
- hosts: dev
  become: True
  tasks:
  - name: 'Creating deployment '
    command: kubectl create deployment myapp --image=dhanrajranvirkar/myapp:${image_version}
  - name: 'exporting deployment'
    command: kubectl expose deployment myapp --type=LoadBalancer --target-port=8080 --port=8080
