---
- hosts: dev
  ignore_errors: yes
  become: True
  tasks:
  - name: 'Deleting old version'
    command: kubectl delete deployment myapp
  - name: 'Deleting old service'
    command: kubectl delete svc myapp
  - name: 'Deploying new version image'
    command: kubectl create deployment myapp --image=dhanrajranvirkar/myapp:"{{ image_version }}"
  - name: 'Creating new service'
    command: kubectl expose deployment myapp --type=NodePort --port=8080 --target-port=8080
