---
- hosts: dev
  become: True
  tasks:
  - name: 'Installing Python3'
    yum:
      name: python3
      state: present
  - name: 'Installing openshift module'
    command: pip3 install openshift
  - name: 'Installing PyYAML'
    command: pip3 install PyYAML
  - name: 'Creating deployment '
    k8s:
      state: present
      src: myapp.yml
  - name: 'exporting deployment'
    k8s:
      state: present
      src: myappservice.yml
