---
- hosts: dev
  ignore_errors: yes
  become: True
  tasks:
  - name: 'Deploying image'
    command: kubectl apply -f myapp.yml
  - name: 'update deployment'
    command: kubectl rollout restart deployment.v1.apps/myapp
  - name: 'create service'
    command: kubectl expose deployment myapp --type=LoadBalancer --port=8080 --target-port=8080
