---
- hosts: dev
  ignore_errors: yes
  become: True
  tasks:
  - name: 'Deploying image'
    command: kubectl create deployment myapp --image=dhanrajranvirkar/myapp:${image_version}
  - name: 'update deployment'
    command: kubectl rollout restart deployment.v1.apps/myapp
  - name: Create a Service object from an inline definition
    command: kubectl expose deployment myapp --type=NodePort --target-port=8080 --port=8080
