apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200
