apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: dhanrajranvirkar/myapp:${image_version}
        name: myapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
